### ISSUE TITLE
From ROS 7.10 the result is wrong 

### ISSUE THREAD

**Issue by iptechnology-coelli** [phistrom/datetime-routeros#1]
tested on CRS328 and CRS112, same result.

7.8:
:put ([$datetime])
A=Friday;H=19;I=07;M=13;S=29;Y=2023;Z=Europe/Rome;a=Fri;b=jul;d=14;date=jul/14/2023;m=07;p=pm;time=19:13:29;w=5;y=23;ymd=2023-07-14;z=+0200
(OK)
--> upgrade, reboot

7.10:
:put ([$datetime])
A=Thursday;H=19;I=07;M=24;S=07;Y=-14;Z=Europe/Rome;a=Thu;b=202;d=-0;date=2023-07-14;m=;p=pm;time=19:24:07;w=4;y=4;ymd=-14---0;z=+0200
(WRONG)

**Comment by iptechnology-coelli** [comment]
the problem is in /system clock get date result:

7.8:
 :put [/system clock get date]
jul/14/2023

7.10:
:put [/system clock get date]
2023-07-14

**Comment by iptechnology-coelli** [comment]
confirmed for other scripts: https://forum.mikrotik.com/viewtopic.php?t=196072

New pull request with fix for Ros 7.10+
It works with both "get date" result

**Comment by phistrom** [comment]
Resolved by commit 3358606
